# Site settings
title: Journey To keep growing
header-img: img/home-bg.png
email: timcev@gmail.com
copyright_name: Timcev1
description: > # this means to ignore newlines until "baseurl:"
  The never ending journey of learning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Timcev1
learn_profile: Timcev1
email_username: timcev@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
